### ISSUE TITLE
We need a logo!

### ISSUE THREAD

**Issue by dfm** [LFITaskForce/FlatironMeeting#65]
The current one isn't very exciting:

<img width="111" alt="Screen Shot 2019-03-21 at 9 41 52 AM" src="https://user-images.githubusercontent.com/350282/54755967-96a7eb00-4bbd-11e9-8adb-0dc6103398d6.png">

cc @danielhey

**Comment by danielhey** [comment]
I'm glad you asked!
![lol2](https://user-images.githubusercontent.com/38233719/54759008-59853c80-4c41-11e9-8310-a22752180489.png)

**Comment by dfm** [comment]
Awesome - thanks! :) I think @EiffL will need to add it to the organization…

**Comment by EiffL** [comment]
Thanks guys, I'm making it the  official logo of the meeting!
